services:
  - type: web
    name: ml-tech-challenge3
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread --threads 4 --timeout 120 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: DATABASE_URL
        fromDatabase:
          name: ml-tech-db
          property: connectionString
